version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: mongodb


  fastapi:
    build: .
    ports:
      - 4850:4850
    depends_on:
      - db

  seeder:
    build: . 
    command: python seederdb/seederdb.py 
    depends_on:
      - db


