version: '3.8'

services:
  db:
    image: mongo:latest #image a créer
    container_name: mongodb #nom du conteneur


  fastapi:
    build: . #on build depuis l'androit de la racine
    ports:
      - 4850:4850 #le port donné
    depends_on:
      - db #le conteneur doit etre dépendant de la bd

  seeder:
    build: ./seederdb #l'androit ou on build notre seeder
    depends_on:
      - db